# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12949ed1f2190bd21178325f7574d0fa2a6bc5a2c1cabc7d6e293ca7ab19bdd368c946dcfbac6e6fab0d0db1b45db5a1bdd502f673b518197a45f763862afd79

test:
  secret_key_base: eecf843fd9cb0414b3de17ff5ee3b870597791c0f8ff0f32b334dd8bd7f66d61aa2b26ef3bcd5c15ecd89d66c2993c9bb20e85128e8187707c85d75ea2784bc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
